-- Multilanguage Tool — migração 2026-08-04
-- Histórico de versões: snapshots do payload inteiro de cada projeto.
-- kind='auto'  → snapshot automático (coalescido no save, no máx 1 a cada 5 min por projeto)
-- kind='backup'→ backup manual do usuário (nunca é podado automaticamente)
--
-- Rodar UMA vez no Supabase (SQL Editor). Idempotente.

create table if not exists project_versions (
  id          bigint generated by default as identity primary key,
  project_id  text        not null,
  payload     jsonb       not null,
  kind        text        not null default 'auto' check (kind in ('auto','backup')),
  label       text,
  author      text,
  created_at  timestamptz not null default now()
);

create index if not exists idx_project_versions_project
  on project_versions (project_id, created_at desc);

create index if not exists idx_project_versions_kind
  on project_versions (project_id, kind, created_at desc);

-- RLS: se o restante das tabelas usa a anon/publishable key com RLS liberado, alinhe aqui.
-- A tool acessa via a mesma publishable key das outras tabelas. Ajuste conforme sua policy atual:
alter table project_versions enable row level security;

drop policy if exists project_versions_all on project_versions;
create policy project_versions_all on project_versions
  for all using (true) with check (true);
